export const web = {
  name: "Doruk Akademi",
  prefix: "doruk",
  headerHeight: "100px",
  phone: "+905406404010",
  email: "dorukakademik@gmail.com",
  webaddr: "https://doruktez.com",
  keywords: [
    "akademik kariyer",
    "yüksek lisans",
    "lisansüstü",
    "master",
    "MBA",
    "akademik dürüstlük",
    "araştırma",
    "burs başvuruları",
    "fonlar",
    "veri analizi",
    "proje yönetimi",
    "zaman yönetimi",
    "akademik yayın etiği",
    "araştırma yöntemi eğitimi",
    "kaynak ve atıf yönetimi",
    "akademik geri bildirim",
    "networking",
    "konferanslar",
    "seminerler",
    "işbirliği",
    "kariyer planlama",
    "endüstriyel yollar",
    "akademik yollar",
  ],
  description: "Etik akademik süreç rehberliği ve araştırma eğitimi",
};
