export const web = {
  name: "Doruk Akademi",
  prefix: "doruk",
  headerHeight: "100px",
  phone: "+905406404010",
  email: "dorukakademik@gmail.com",
  webaddr: "https://dorukakademi.com",
  keywords: [
    "akademik kariyer",
    "yüksek lisans",
    "lisansüstü",
    "master",
    "MBA",
    "intihal",
    "araştırma",
    "burs başvuruları",
    "fonlar",
    "veri analizi",
    "proje yönetimi",
    "zaman yönetimi",
    "akademik makale yazma",
    "networking",
    "konferanslar",
    "seminerler",
    "işbirliği",
    "kariyer planlama",
    "endüstriyel yollar",
    "akademik yollar",
  ],
  description: "Akademik kariyer asistanı",
};
